# AlertManager config file

route:
  # To aggregate alerts
  group_by: ["alertname"]

  # How long to initially wait to send a notification for a group
  group_wait: 3s

  # How long to wait before sending a notification about new alerts
  group_interval: 5s

  # How long to wait before sending a notification again if it has already been sent successfully for an alert
  repeat_interval: 1h

  # Name of the receiver group to notify
  receiver: slack-receiver

receivers:
  - name: "slack-receiver"
    slack_configs:
      - api_url: https://hooks.slack.com/services/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
        channel: "alertmanager"
        send_resolved: true
        icon_url: https://avatars3.githubusercontent.com/u/3380462
        text: >-
          {{ range .Alerts -}}
          *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
          *Description:* {{ .Annotations.description }}
          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}

  - name: "mail-receiver"
# email_configs:
#   - to: 'emails of the ones that need to be notified'
#     send_resolved: true
#     smtp_from:
#     smtp_smarthost:
#     smtp_auth_username:
#     smtp_auth_password:
